In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [2]:
loan_data = pd.read_csv('test_AV3.csv')

In [3]:
loan_data

Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Urban           Y  
2               1.0         Urban           Y  
3               NaN         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
362             1.0         Urban           Y  
363             1.0         Urban           Y  
364             NaN     Semiurban           Y  
365             1.0         Rural           Y  
366             1.0         Rural           Y  

[367 rows x 13 columns]

In [4]:
loan_data.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
loan_data['Gender'].fillna(loan_data['Gender'].mode()[0], inplace = True)
loan_data['Dependents'].fillna(loan_data['Dependents'].mode()[0], inplace = True)
loan_data['Self_Employed'].fillna(loan_data['Self_Employed'].mode()[0], inplace = True)
loan_data['Credit_History'].fillna(loan_data['Credit_History'].mode()[0], inplace = True)

In [6]:
loan_data['LoanAmount'].fillna(loan_data['LoanAmount'].median(), inplace = True)

In [7]:
loan_data['Loan_Amount_Term'].fillna(loan_data['Loan_Amount_Term'].median(), inplace = True)

In [8]:
loan_data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [9]:
loan_data.Education=label.fit_transform(loan_data.Education)

In [10]:
loan_data['Property_Area']=label.fit_transform(loan_data['Property_Area'])

In [11]:
loan_data['Loan_Status']=label.fit_transform(loan_data['Loan_Status'])

In [12]:
loan_data['Self_Employed']=label.fit_transform(loan_data['Self_Employed'])

In [13]:
loan_data['Dependents']=label.fit_transform(loan_data['Dependents'])

In [14]:
loan_data.dtypes


Loan_ID               object
Gender                object
Married               object
Dependents             int32
Education              int32
Self_Employed          int32
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int32
Loan_Status            int32
dtype: object

In [15]:
loan_data = loan_data.drop(['Loan_ID','Gender','Married','Self_Employed'],axis = 1)

In [16]:
X= loan_data.drop('Loan_Status',axis=1)

In [17]:
y= loan_data.Loan_Status

LOGISTIC REGRESSION

In [18]:
from sklearn.model_selection import train_test_split,cross_val_score

In [19]:
x_train, x_cv, y_train, y_cv = train_test_split(X,y, test_size =0.2)

In [20]:
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

In [21]:
model_LR = LogisticRegression(max_iter = 400, random_state = 1) 
model_LR.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=400,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
pred_cv = model_LR.predict(x_cv)

In [23]:
LR = accuracy_score(pred_cv,y_cv)
LR

1.0

In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
cm_LR = confusion_matrix(pred_cv,y_cv)

In [26]:
cm_LR

array([[14,  0],
       [ 0, 60]], dtype=int64)

SUPPORT VECTOR  MACHINE

In [27]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 2)
classifier.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=2, shrinking=True, tol=0.001,
    verbose=False)

In [28]:
pred_svc = classifier.predict(x_cv)

In [29]:
SVC = accuracy_score(y_cv,pred_svc)
SVC

0.972972972972973

In [30]:
cm_SVC = confusion_matrix(y_cv, pred_svc)

In [31]:
cm_SVC

array([[13,  1],
       [ 1, 59]], dtype=int64)

In [32]:
from sklearn.preprocessing import StandardScaler as ss

In [33]:
scaler=ss()

In [34]:
scaler.fit(loan_data.drop('Loan_Status',axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [35]:
sf=scaler.transform(loan_data.drop('Loan_Status',axis=1))

In [36]:
scaled_loan=pd.DataFrame(sf,columns=loan_data.columns[:-1])

In [37]:
scaled_loan

Dependents  Education  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0     -0.758222  -0.544812         0.186461          -0.673335   -0.426780   
1      0.181871  -0.544812        -0.352692          -0.029848   -0.163953   
2      1.121964  -0.544812         0.039641           0.098849    1.183033   
3      1.121964  -0.544812        -0.502774           0.418877   -0.591047   
4     -0.758222   1.835497        -0.311909          -0.673335   -0.952433   
..          ...        ...              ...                ...         ...   
362    2.062056   1.835497        -0.162439           0.088982   -0.377500   
363   -0.758222  -0.544812        -0.132056          -0.369180   -0.344647   
364   -0.758222  -0.544812        -0.317211           0.181644   -0.163953   
365   -0.758222  -0.544812         0.039641           0.353241    0.361700   
366   -0.758222  -0.544812         0.896087          -0.673335   -0.623900   

     Loan_Amount_Term  Credit_History  Property_Area  
0            0.266022        0.437674       1.118764  
1            0.266022        0.437674       1.118764  
2            0.266022        0.437674       1.118764  
3            0.266022        0.437674       1.118764  
4            0.266022        0.437674       1.118764  
..                ...             ...            ...  
362          0.266022        0.437674       1.118764  
363          0.266022        0.437674       1.118764  
364          0.266022        0.437674      -0.095989  
365          0.266022        0.437674      -1.310741  
366         -2.521639        0.437674      -1.310741  

[367 rows x 8 columns]

In [38]:
X2=scaled_loan

In [39]:
y2=loan_data['Loan_Status']

In [40]:
X_train2, X_test2 ,y_train2, y_test2= train_test_split(X2,y2, test_size=0.3)

K-NEAREST NEIGHBOUR

In [41]:
from sklearn.neighbors import KNeighborsClassifier
classifier_K = KNeighborsClassifier(n_neighbors=4)
classifier_K.fit(X_train2, y_train2)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [42]:
cross_val_score(classifier_K,X2,y2,cv=2)

array([0.99456522, 0.99453552])

In [43]:
pred_K=classifier_K.predict(X_test2)

In [44]:
KNN = accuracy_score(y_test2,pred_K)
KNN

1.0

In [45]:
cm_K = confusion_matrix(y_test2,pred_K)

In [46]:
cm_K

array([[15,  0],
       [ 0, 96]], dtype=int64)

DECISION TREE

In [47]:
from sklearn.tree import DecisionTreeClassifier

In [49]:
sc_X = ss()

In [50]:
clf = DecisionTreeClassifier(random_state = 1)

In [51]:
clf.fit(X_train2, y_train2)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1, splitter='best')

In [52]:
pred_dt = clf.predict(x_cv)

In [53]:
DT = accuracy_score(y_cv,pred_dt)
DT

0.8108108108108109

In [54]:
cm_dt = confusion_matrix(y_cv,pred_dt)

In [55]:
cm_dt

array([[ 0, 14],
       [ 0, 60]], dtype=int64)

In [56]:
print("Accuracy of the models: \n LR: \t %f \n SVC: \t %f \n KNN: \t %f \n DT: \t %f" % (LR,SVC,KNN,DT))

Accuracy of the models: 
 LR: 	 1.000000 
 SVC: 	 0.972973 
 KNN: 	 1.000000 
 DT: 	 0.810811
